In [2]:
#Use For loop to access elements
import numpy as np
i = np.array([10, 20, 30, 40, 50, 70])
for j in i:
    print(j)

10
20
30
40
50
70


In [5]:
#Access 2-D Elements
import numpy as np
i = np.array([[10, 20, 30], [40, 50, 60], [70,80,90]])
for j in i:
  print(j)

[10 20 30]
[40 50 60]
[70 80 90]


In [6]:
#Nested For loop
import numpy as np
i = np.array([[10, 20, 30], [40, 50, 60], [70,80,90]])
for j in i:
    for k in j:
        print(k)

10
20
30
40
50
60
70
80
90


In [7]:
#Access 3-D Elements
import numpy as np
i = np.array([
[[10, 20, 30], [40, 50, 60], [70,80,90]],
[[1, 2, 3], [4, 5, 6], [7,8,9]],
[[10, 20, 30], [40, 50, 60], [70,80,90]],
])
for j in i:
   print(j)



[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [8]:
import numpy as np
i = np.array([
[[10, 20, 30], [40, 50, 60], [70,80,90]],
[[1, 2, 3], [4, 5, 6], [7,8,9]],
[[10, 20, 30], [40, 50, 60], [70,80,90]],
])
for j in i:
  for k in j:
     for m in k:
        print(m)

10
20
30
40
50
60
70
80
90
1
2
3
4
5
6
7
8
9
10
20
30
40
50
60
70
80
90
